language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: stephenwpoole@gmail.com
  on:
    tags: true
    branch: master
script:
- npm install codecov -g
- npm install
- npm test
- npm start
env:
  global:
    secure: P703tbf/CRlRP2sBeUCAUFQEEC2LjYvjeeYkwCmVxJDNX4jx9ZEqTEOgs4YkpAKuKje45DPSBkLKFDllSqkFThjhbQUpwV+d5NG8KOBYhwVReG4zmR8WtYu56EHkds2YEtcAp18VpF4+w6sjwoZbt0EtatSz9BW9ABKyp/DbcB4d5J/ktm5HZcXsAReRS58ZgfqFI/9gtGTbB3/aa3iRIkfBXuFqNdLSf2QKL3bl3irKxiVrB4MaPRA8ojKidqTkwIfhBgbWqPUh3vL4+Qhct3SX5qOB89Ypu1k/OMGlubQ6Ac8Nk5WiTAZqAlhtNIWeMb0bjlM8UNjevbFDAQHKLnQZo3nnsW7UIi1lqSxLcY0nex5g5W+N2kNGgYU90ff9p9K9VGNA3MBh7TPlA45gb42N+l0LHOqXQt8cKRUwtILghcmV7jMbulE6JTTaf5avP6AA28UY6n0FXvSy7qrJ/jSAHSaGMdjruOzOcZ/e4OYoPotylccA2Y0Aml5es9NX/1HF1HSx5QLPi/Tj5DAAgvYT139K5mRdY5qX5M5lY9OJg2iT6xf4STD7yb6g2h75lcN70+PFWW802y5mLfSAqJQTZuHZyRY+XUzcTUHoyFn6cF86IflpC1I4vg7Y7b9yxCmzkYfwbaM2LCVhs4dVv29M0ZYJiY/iBOtKrkHO0k8=
after_success:
    - nyc report --reporter=json > coverage/coverage.json && codecov